name : Package building

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install ROS2
      run: |
          sudo apt update && sudo apt install curl gnupg2 lsb-release
          sudo curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
          sudo apt install ros-humble-desktop  # Adjust ROS2 distro as needed

      # Install colcon
    - name: Install colcon
      run: sudo apt install python3-colcon-common-extensions


    - name: Create workspace
      run: |
        mkdir -p ~/rosdev_ws/src
        cd ~/rosdev_ws/src
        git clone --recurse-submodules https://github.com/noshluk2/robot_control.git
        cd robot_control
        chmod +x packages_setup.sh

    - name: Run setup script
      run: |
        cd ~/rosdev_ws/src
        bash robot_control/packages_setup.sh
